#!/bin/bash
set -x
GTEST_DIR=/pica/h1/afshin/gtest/gtest-1.7.0
LD_LIBRARY_PATH=$GTEST_DIR/lib/.libs:$LD_LIBRARY_PATH
#ipn=2;P=2;p=2;q=1;nt=2;DLB=1;ps=2000;B=7;b=6;to=30;N=2520
ipn=2;P=2;p=1;q=2;nt=2;DLB=0;ps=2000 ;B=2;b=2;to=3;N=24
#P=1;q=1;p=1;ipn=1
params_long="--num-proc $P --proc-grid-row $p --proc-grid-col $q --data-rows $N $B $b --ipn $ipn --timeout $to --num-threads $nt --poll-sleep $ps "
outpath=../temp
apppath=../bin

run_test(){
    mkdir -p $outpath/$1
    outfile=$outpath/$1/$1.out
    appfile=$apppath/$1.test
    test_result=$outpath/$1/$1.test.result
    rm ${test_result} ${outfile} > /dev/null 2>&1
    if [ "x$2" == "x" ] ; then
	mpirun -n $P -tag-output $appfile ${params_long} 1>${test_result} 2>$outfile    
	cat ${test_result} | grep "\[1,0\]"
     #$appfile  
    else
	mpirun -n $P -tag-output $appfile ${params_long} 1>${test_result} 2>$outfile    
     #$appfile  1>${test_result} 2>$outfile    
	cat ${test_result} | grep "\[1,0\]"   
    fi
}
if [ "x$1" == "xclean" ] ; then 
    curd=$(pwd)
    cd ../../../examples	
    ./run clean
    cd $curd
    echo $(pwd)
fi

make clean
make

run_test ml_basic $1
rm dt_*.txt sg_*.txt > /dev/null 2>&1
