#!/bin/bash
make clean
make
set +x
GTEST_DIR=/pica/h1/afshin/gtest/gtest-1.7.0
LD_LIBRARY_PATH=$GTEST_DIR/lib/.libs:$LD_LIBRARY_PATH
P=2;p=2;q=1;DLB=0;nt=1;ipn=1;
params="$p $q 48 8 2 $nt $DLB $ipn 2"
outpath=./temp
apppath=./bin

run_test(){
    mkdir -p $outpath/$@
    outfile=$outpath/$@/$@.out
    appfile=$apppath/$@.test
    test_result=$outpath/$@/$@.test.result
    mpirun -n $P -tag-output $appfile $params 1>${test_result} 2>$outfile
    grep -i "\[1,0\]" $outfile > ${outfile}.0
    grep -i "\[1,1\]" $outfile > ${outfile}.1
    args=$@
    t=${args//_/ }
    echo "=========================================================================="
    echo "                                ${t^^}"
    echo "=========================================================================="
    cat ${test_result}    
    echo ""
    echo ""
    
}
run_test mt_admin


P=2;p=2;q=1;DLB=0;nt=1;ipn=2;
params="$p $q 48 2 2 $nt $DLB $ipn 3"
run_test mt_mbox


run_test mt_work

rm dt_*.* sg_*.txt > /dev/null 2>&1
