#!/bin/bash

SUPERGLUE_DIR="../../../superglue/include"
SUPERGLUE_FLAGS="-pthread -I${SUPERGLUE_DIR}"
pars="1 2 1200 10 5 1 0 1"

rm t.o ./tc

mpic++ -c test_contexts.cpp ${SUPERGLUE_FLAGS} -o t.o
mpic++ t.o -lm -lrt -L/opt/openmpi/1.6intel13.1/lib -lstdc++ -o tc
mpirun -np 2 --output-filename ctx.out ./tc $pars
#> a.txt
#grep "\[" a.txt | sort -V -k1,1 >b.txt
#cat a.txt