#! /bin/bash


# params:   p q N B b
ipn=4
P=4
p=4;q=1
nt=4
DLB=0
params[1]="$p $q 48 8 2 $nt $DLB $ipn 10"
ACML_DIR=/home/afshin/acml/acmllib/ifort64_fma4
ACML_LIB=$ACML_DIR/lib/libacml.a

export LD_LIBRARY_PATH=$ACML_DIR/lib:$LD_LIBRARY_PATH

mpirun -n $P -npernode $ipn --output-filename test.out ./cholesky

